local version = import "version.jsonnet";
{
    cassandra: "docker.io/cassandra:4.1.10",
    neo4j: "docker.io/neo4j:2025.08.0-community-bullseye",
    pulsar: "docker.io/apachepulsar/pulsar:4.1.0",
    pulsar_manager: "docker.io/apachepulsar/pulsar-manager:v0.4.0",
    etcd: "quay.io/coreos/etcd:v3.6.4",
    minio: "docker.io/minio/minio:RELEASE.2025-09-07T16-13-09Z",
    milvus: "docker.io/milvusdb/milvus:v2.5.17",
    prometheus: "docker.io/prom/prometheus:v3.5.0",
    grafana: "docker.io/grafana/grafana:12.1.1",
    trustgraph_base: "docker.io/trustgraph/trustgraph-base:" + version,
    trustgraph_flow: "docker.io/trustgraph/trustgraph-flow:" + version,
    trustgraph_ocr: "docker.io/trustgraph/trustgraph-ocr:" + version,
    trustgraph_bedrock: "docker.io/trustgraph/trustgraph-bedrock:" + version,
    trustgraph_vertexai: "docker.io/trustgraph/trustgraph-vertexai:" + version,
    trustgraph_hf: "docker.io/trustgraph/trustgraph-hf:" + version,
    trustgraph_mcp: "docker.io/trustgraph/trustgraph-mcp:" + version,
    qdrant: "docker.io/qdrant/qdrant:v1.15.4",
    memgraph_mage: "docker.io/memgraph/memgraph-mage:3.5",
    memgraph_lab: "docker.io/memgraph/lab:3.5.0",
    falkordb: "docker.io/falkordb/falkordb:v4.12.5",
    "workbench-ui": "docker.io/trustgraph/workbench-ui:1.4.2",
    "ddg-mcp-server": "docker.io/trustgraph/ddg-mcp-server:0.1.0",
    "tgi-service-intel-xpu": "ghcr.io/huggingface/text-generation-inference:3.3.1-intel-xpu",
    "tgi-service-cpu": "ghcr.io/huggingface/text-generation-inference:3.3.1-intel-cpu",
    "tgi-service-gaudi": "ghcr.io/huggingface/text-generation-inference:sha-f140440-gaudi",
    "vllm-service-intel-xpu": "docker.io/intel/vllm:0.8.0-xpu",
    "vllm-service-gaudi": "docker.io/trustgraph/vllm-hpu:027f5645",
    "vllm-service-nvidia": "docker.io/vllm/vllm-openai:latest",
}
