{
 "title": "Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Knowledge extraction backlog",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "producer_count_total{processor=\"chunker\",name=\"output\"}\n- ignoring(instance, job, processor, name, status)\nprocessing_count_total{processor=\"kg-extract-relationships\", name=\"input\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Graph embeddings backlog",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(producer_count_total{processor=\"graph-embeddings\",name=\"output\"} - ignoring(instance, job, processor, name, status) processing_count_total{processor=\"ge-write\",name=\"input\"} >= 2)\nor\n(0 * (producer_count_total{processor=\"graph-embeddings\",name=\"output\"} - ignoring(instance, job, processor, name, status) processing_count_total{processor=\"ge-write\",name=\"input\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Triples backlog",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "(clamp_min(\n  (\n    producer_count_total{processor=\"kg-extract-definitions\",name=\"triples\"}\n    + on(flow)\n    producer_count_total{processor=\"kg-extract-relationships\",name=\"triples\"}\n  )\n  - on(flow) processing_count_total{processor=\"triples-write\",name=\"input\"},\n  0\n) >= 2) or (0 * clamp_min(\n  (\n    producer_count_total{processor=\"kg-extract-definitions\",name=\"triples\"}\n    + on(flow)\n    producer_count_total{processor=\"kg-extract-relationships\",name=\"triples\"}\n  )\n  - on(flow) processing_count_total{processor=\"triples-write\",name=\"input\"},\n  0\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LLM latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(le) (rate(text_completion_duration_bucket[$__rate_interval]))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by(status) (rate(processing_count_total{status!=\"success\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by(processor) (rate(request_latency_count{processor!=\"config-svc\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Pub/sub backlog",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "pulsar_msg_backlog{topic!=\"persistent://tg/config/config\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Chunk size",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "max by(le) (chunk_size_bucket)", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "Rate limit events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by(job) (increase(rate_limit_count_total[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes / 1073741824",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Models in use",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
   "targets": [
    { "expr": "sum by (model) (tokens_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tokens",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
   "targets": [
    {
     "expr": "sum by(model, direction)  (rate(tokens_total[$__rate_interval]))",
     "legendFormat": "{{model}} - {{direction}}"
    }
   ]
  },
  {
   "title": "Token cost",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
   "targets": [
    {
     "expr": "sum by(direction, model) (rate(tokens_total[$__rate_interval]))",
     "legendFormat": "{{model}} - {{direction}}"
    }
   ]
  }
 ]
}