#!/usr/bin/env python3

import requests

url = "http://localhost:8088/"

resp = requests.post(
    f"{url}/api/v1/flow",
    json={
        "operation": "get-class",
        "class-name": "default",
    }
)

resp = resp.json()

print(resp["class-definition"])


