#!/usr/bin/env python3

import pulsar
from trustgraph.clients.llm_client import LlmClient

llm = LlmClient(pulsar_host="pulsar://localhost:6650")

prompt="What is 2 + 12?"

try:
    resp = llm.request(prompt)
    print(resp)
except Exception as e:
    print(f"{e.__class__.__name__}: {e}")

