#!/usr/bin/env python3

import requests
import json

url = "http://localhost:8088/"

resp = requests.post(
    f"{url}/api/v1/flow",
    json={
        "operation": "stop-flow",
        "flow-id": "0003",
    }
)

print(resp)
print(resp.text)
resp = resp.json()


print(resp)

