#!/usr/bin/env python3

import pulsar
from trustgraph.graph_rag_client import GraphRagClient

rag = GraphRagClient(pulsar_host="pulsar://localhost:6650")

query="""List 20 key points to describe the research that led to the discovery of Leo VI.
"""

resp = rag.request(query)

print(resp)

