#!/usr/bin/env python3

import pulsar
from trustgraph.embeddings_client import EmbeddingsClient

embed = EmbeddingsClient(pulsar_host="pulsar://localhost:6650")

prompt="Write a funny limerick about a llama"

resp = embed.request(prompt)

print(resp)



