#!/usr/bin/env python3

import pulsar
from trustgraph.clients.prompt_client import PromptClient

p = PromptClient(pulsar_host="pulsar://localhost:6650")

question = """What is the square root of 16?"""

resp = p.request(
    id="question",
    terms = {
        "question": question,
        "attitude": "Spanish-speaking bot"
    }
)

print(resp)

