#!/usr/bin/env python3

import json
import textwrap
from trustgraph.clients.agent_client import AgentClient

def wrap(text, width=75):

    if text is None: text = "n/a"

    out = textwrap.wrap(
        text, width=width
    )
    return "\n".join(out)

def output(text, prefix="> ", width=78):

    out = textwrap.indent(
        text, prefix=prefix
    )
    print(out)

p = AgentClient(pulsar_host="pulsar://localhost:6650")

q = "How many cats does Mark have? Calculate that number raised to 0.4 power.  Is that number lower than the numeric part of the mission identifier of the Space Shuttle Challenger on its last mission?  If so, give me an apple pie recipe, otherwise return a poem about cheese."

output(wrap(q), "\U00002753 ")
print()

def think(x):
    output(wrap(x), "\U0001f914 ")
    print()

def observe(x):
    output(wrap(x), "\U0001f4a1 ")
    print()

resp = p.request(
    question=q, think=think, observe=observe,
)

output(resp, "\U0001f4ac ")
print()

