#!/usr/bin/env python3

import pulsar
from trustgraph.graph_rag_client import GraphRagClient

rag = GraphRagClient(pulsar_host="pulsar://localhost:6650")

query="""Write a blog post describing the key points desribing the researcher's methodology for finding Leo VI.
"""

resp = rag.request(query)

print(resp)

