#!/usr/bin/env python3

import pulsar
from trustgraph.graph_rag_client import GraphRagClient

rag = GraphRagClient(pulsar_host="pulsar://localhost:6650")

query="""
Identify any facts which provide an explanation of the explosion of the
space shuttle rocket boosters"""

resp = rag.request(query)

print(resp)

