#!/usr/bin/env python3

import requests
import json
import sys
import base64

url = "http://localhost:8088/api/v1/"

############################################################################

id = "http://trustgraph.ai/doc/12345678"

with open("docs/README.cats") as f:
    doc = base64.b64encode(f.read().encode("utf-8")).decode("utf-8")

input = {
    "operation": "add",
    "document": {
        "id": id,
        "metadata": [
            {
                "s": {
                    "v": id,
                    "e": True,
                },
                "p": {
                    "v": "http://www.w3.org/2000/01/rdf-schema#label",
                    "e": True,
                },
                "o": {
                    "v": "Mark's pets", "e": False,
                },
            },
            {
                "s": {
                    "v": id,
                    "e": True,
                },
                "p": {
                    "v": 'https://schema.org/keywords',
                    "e": True,
                },
                "o": {
                    "v": "cats", "e": False,
                },
            },
        ],
        "document": doc,
        "kind": "text/plain",
        "user": "trustgraph",
        "collection": "default",
        "title": "Mark's cats",
        "comments": "Test doc taken from the TrustGraph repo",
    }
}

resp = requests.post(
    f"{url}librarian",
    json=input,
)

print(resp.text)
resp = resp.json()

print(resp)

if "error" in resp:
    print(f"Error: {resp['error']}")
    sys.exit(1)

# print(resp["response"])
print(resp)

sys.exit(0)

############################################################################

