#!/usr/bin/env python3

import requests
import json
import sys

url = "http://localhost:8088/api/v1/flow/0000/agent"

############################################################################

input = {
    "question": "What is the highest risk aspect of running a space shuttle program?  Provide 5 detailed reasons to justify our answer.",
}

resp = requests.post(
    url,
    json=input,
)

print(resp.text)
resp = resp.json()

if "error" in resp:
    print(f"Error: {resp['error']}")
    sys.exit(1)

print(resp["answer"])

