#!/usr/bin/env python3

import requests
import json
import sys

url = "http://localhost:8088/api/v1/flow/0000/graph-rag"

############################################################################

input = {
    "query": "Give me 10 facts",
}

resp = requests.post(
    url,
    json=input,
)

resp = resp.json()

print(resp)
if "error" in resp:
    print(f"Error: {resp['error']}")
    sys.exit(1)

print(resp["response"])

sys.exit(0)
############################################################################

