
# ----------------------------------------------------------------------------
# Build an AI container.  This does the torch install which is huge, and I
# like to avoid re-doing this.
# ----------------------------------------------------------------------------

FROM docker.io/fedora:42 AS ai

ENV PIP_BREAK_SYSTEM_PACKAGES=1

RUN dnf install -y python3.12 && \
  alternatives --install /usr/bin/python python /usr/bin/python3.12 1 && \
  python -m ensurepip --upgrade && \
  pip3 install --no-cache-dir build wheel aiohttp && \
  pip3 install --no-cache-dir pulsar-client==3.7.0 && \
  dnf clean all

RUN pip3 install torch==2.5.1+cpu \
    --index-url https://download.pytorch.org/whl/cpu

RUN pip3 install --no-cache-dir \
    langchain==0.3.25 langchain-core==0.3.60 langchain-huggingface==0.2.0 \
    langchain-community==0.3.24 \
    sentence-transformers==4.1.0 transformers==4.51.3 \
    huggingface-hub==0.31.2 \
    pulsar-client==3.7.0

# Most commonly used embeddings model, just build it into the container
# image
RUN huggingface-cli download sentence-transformers/all-MiniLM-L6-v2

# ----------------------------------------------------------------------------
# Build a container which contains the built Python packages.  The build
# creates a bunch of left-over cruft, a separate phase means this is only
# needed to support package build
# ----------------------------------------------------------------------------

FROM ai AS build

COPY trustgraph-base/ /root/build/trustgraph-base/
COPY trustgraph-flow/ /root/build/trustgraph-flow/
COPY trustgraph-vertexai/ /root/build/trustgraph-vertexai/
COPY trustgraph-bedrock/ /root/build/trustgraph-bedrock/
COPY trustgraph-embeddings-hf/ /root/build/trustgraph-embeddings-hf/
COPY trustgraph-cli/ /root/build/trustgraph-cli/

WORKDIR /root/build/

RUN pip3 wheel -w /root/wheels/ --no-deps ./trustgraph-base/
RUN pip3 wheel -w /root/wheels/ --no-deps ./trustgraph-flow/
RUN pip3 wheel -w /root/wheels/ --no-deps ./trustgraph-vertexai/
RUN pip3 wheel -w /root/wheels/ --no-deps ./trustgraph-bedrock/
RUN pip3 wheel -w /root/wheels/ --no-deps ./trustgraph-embeddings-hf/
RUN pip3 wheel -w /root/wheels/ --no-deps ./trustgraph-cli/

RUN ls /root/wheels

# ----------------------------------------------------------------------------
# Finally, the target container.  Start with base and add the package.
# ----------------------------------------------------------------------------

FROM ai

COPY --from=build /root/wheels /root/wheels

RUN \
    pip3 install /root/wheels/trustgraph_base-* && \
    pip3 install /root/wheels/trustgraph_flow-* && \
    pip3 install /root/wheels/trustgraph_vertexai-* && \
    pip3 install /root/wheels/trustgraph_bedrock-* && \
    pip3 install /root/wheels/trustgraph_embeddings_hf-* && \
    pip3 install /root/wheels/trustgraph_cli-* && \
    pip3 cache purge && \
    rm -rf /root/wheels

WORKDIR /

CMD sleep 1000000

