#!/usr/bin/env python3

"""
Connects to the graph query service and dumps all graph edges.
"""

import argparse
import os
from trustgraph.api import Api

default_url = os.getenv("TRUSTGRAPH_URL", 'http://localhost:8088/')
default_user = 'trustgraph'
default_collection = 'default'

def show_graph(url, user, collection):

    api = Api(url)

    rows = api.triples_query(
#         user=user, collection=collection,
        s=None, p=None, o=None, limit=10_000,
    )

    for row in rows:
        print(row.s, row.p, row.o)

def main():

    parser = argparse.ArgumentParser(
        prog='tg-graph-show',
        description=__doc__,
    )

    parser.add_argument(
        '-u', '--api-url',
        default=default_url,
        help=f'API URL (default: {default_url})',
    )

    parser.add_argument(
        '-U', '--user',
        default=default_user,
        help=f'User ID (default: {default_user})'
    )

    parser.add_argument(
        '-C', '--collection',
        default=default_collection,
        help=f'Collection ID (default: {default_collection})'
    )
        
    # parser.add_argument(
    #     '--pulsar-api-key',
    #     default=default_pulsar_api_key,
    #     help=f'Pulsar API key',
    # )
    
    args = parser.parse_args()

    try:

        show_graph(
            url=args.api_url,
            user=args.user,
            collection=args.collection,
            pulsar_api_key=args.pulsar_api_key,
        )

    except Exception as e:

        print("Exception:", e, flush=True)

main()

