#!/usr/bin/env python3

"""
Connects to the graph query service and dumps all graph edges.
"""

import argparse
import os
from trustgraph.clients.triples_query_client import TriplesQueryClient

default_pulsar_host = os.getenv("PULSAR_HOST", 'pulsar://localhost:6650')
default_pulsar_api_key = os.getenv("PULSAR_API_KEY", None)
default_user = 'trustgraph'
default_collection = 'default'

def show_graph(pulsar, user, collection, pulsar_api_key=None):

    tq = TriplesQueryClient(pulsar_host=pulsar, pulsar_api_key=pulsar_api_key)

    rows = tq.request(
        user=user, collection=collection,
        s=None, p=None, o=None, limit=10_000_000
    )

    for row in rows:
        print(row.s.value, row.p.value, row.o.value)

def main():

    parser = argparse.ArgumentParser(
        prog='tg-graph-show',
        description=__doc__,
    )

    parser.add_argument(
        '-p', '--pulsar-host',
        default=default_pulsar_host,
        help=f'Pulsar host (default: {default_pulsar_host})',
    )

    parser.add_argument(
        '-u', '--user',
        default=default_user,
        help=f'User ID (default: {default_user})'
    )

    parser.add_argument(
        '-c', '--collection',
        default=default_collection,
        help=f'Collection ID (default: {default_collection})'
    )
        
    parser.add_argument(
        '--pulsar-api-key',
        default=default_pulsar_api_key,
        help=f'Pulsar API key',
    )
    
    args = parser.parse_args()

    try:

        show_graph(
            pulsar=args.pulsar_host, user=args.user,
            collection=args.collection,
            pulsar_api_key=args.pulsar_api_key,
        )

    except Exception as e:

        print("Exception:", e, flush=True)

main()

