[
    import "patterns/pulsar.jsonnet",
    import "patterns/trustgraph-base.jsonnet",
    import "patterns/graph-rag-cassandra.jsonnet",
    import "patterns/graph-rag-neo4j.jsonnet",
    import "patterns/prompt-template-kg-query.jsonnet",
    import "patterns/prompt-template-definitions.jsonnet",
    import "patterns/prompt-template-relationships.jsonnet",
    import "patterns/prompt-template-document-query.jsonnet",
    import "patterns/prompt-template-rows-template.jsonnet",
    import "patterns/override-recursive-chunker.jsonnet",
    import "patterns/llm-azure.jsonnet",
    import "patterns/llm-bedrock.jsonnet",
    import "patterns/llm-claude.jsonnet",
    import "patterns/llm-cohere.jsonnet",
    import "patterns/llm-ollama.jsonnet",
    import "patterns/llm-openai.jsonnet",
    import "patterns/llm-vertexai.jsonnet",
    import "patterns/pulsar-manager.jsonnet",
    import "patterns/vector-store-milvus.jsonnet",
    import "patterns/vector-store-qdrant.jsonnet",
]
