#!/usr/bin/env python3

from trustgraph.graph_rag import GraphRag
import sys

query = " ".join(sys.argv[1:])

gr = GraphRag(
    verbose=True,
    vector_store="http://localhost:19530",
    pulsar_host="pulsar://localhost:6650",
    graph_hosts=["localhost"],
)

if query == "":
    query="""This knowledge graph describes the Space Shuttle disaster.
Present 20 facts which are present in the knowledge graph."""

resp = gr.query(query)
print(resp)

