#!/usr/bin/env python3

from trustgraph.graph_rag import GraphRag
import sys

query = " ".join(sys.argv[1:])

gr = GraphRag(
    verbose=True,
    pulsar_host="pulsar://localhost:6650",
    completion_request_queue="non-persistent://tg/request/text-completion-rag",
    completion_response_queue="non-persistent://tg/response/text-completion-rag-response",
)

if query == "":
    query="""This knowledge graph describes the Space Shuttle disaster.
Present 20 facts which are present in the knowledge graph."""

resp = gr.query(query)
print(resp)

