
name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:

  get-version:

    name: Determine version
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.version.outputs.VERSION }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: version
        run: echo VERSION=$(git describe --exact-match --tags | sed 's/^v//') >> $GITHUB_OUTPUT

  python-packages:

    name: Release Python packages
    runs-on: ubuntu-24.04
    needs: get-version
    permissions:
      contents: write
      id-token: write
    environment:
      name: release

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install build wheel

      - name: Build packages
        run: make packages VERSION=${{ needs.get-version.outputs.version }}

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  container-base:
    name: base
    needs: get-version
    uses: ./.github/workflows/build-container.yaml
    with:
      container: base
      version: ${{ needs.get-version.outputs.version }}
    secrets:
      DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}

  container-flow:
    name: flow
    needs: get-version
    uses: ./.github/workflows/build-container.yaml
    with:
      container: flow
      version: ${{ needs.get-version.outputs.version }}
    secrets:
      DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}

  container-bedrock:
    name: bedrock
    needs: get-version
    uses: ./.github/workflows/build-container.yaml
    with:
      container: bedrock
      version: ${{ needs.get-version.outputs.version }}
    secrets:
      DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}

  container-vertexai:
    name: vertexai
    needs: get-version
    uses: ./.github/workflows/build-container.yaml
    with:
      container: vertexai
      version: ${{ needs.get-version.outputs.version }}
    secrets:
      DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}

  container-hf:
    name: hf
    needs: get-version
    uses: ./.github/workflows/build-container.yaml
    with:
      container: hf
      version: ${{ needs.get-version.outputs.version }}
    secrets:
      DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}

  container-ocr:
    name: ocr
    needs: get-version
    uses: ./.github/workflows/build-container.yaml
    with:
      container: ocr
      version: ${{ needs.get-version.outputs.version }}
    secrets:
      DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}

  container-docling:
    name: docling
    needs: get-version
    uses: ./.github/workflows/build-container.yaml
    with:
      container: docling
      version: ${{ needs.get-version.outputs.version }}
    secrets:
      DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}

  container-mcp:
    name: mcp
    needs: get-version
    uses: ./.github/workflows/build-container.yaml
    with:
      container: mcp
      version: ${{ needs.get-version.outputs.version }}
    secrets:
      DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}
